#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Homebrew completions
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi

# Open new tab in current directory
[[ -f /etc/profile.d/vte.sh ]] && . /etc/profile.d/vte.sh

# set terminal for i3
# export TERMINAL=kitty

# Make python3 the default
export PATH=/usr/local/opt/python/libexec/bin:$PATH

# Add Rust path
export PATH=$HOME/.cargo/bin:$PATH

# Make VSCode trash work
export ELECTRON_TRASH=gio

# Golang setup
export GOPATH=$HOME/code/go
# export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

# Add Python scripts to path
export PATH=$PATH:$HOME/.local/bin

# Prevent Next.js telemetry
export NEXT_TELEMETRY_DISABLED=1

alias pulseup=~/.local/pulse_up
alias pulsedown=~/.local/pulse_down
