#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Setup Node Version Manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# Add Rust to path
export PATH="$HOME/.cargo/bin:$PATH"

# Add RVM
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# Add Yarn
export PATH="$HOME/.yarn/bin:$PATH"

# Golang setup
export GOPATH=$HOME/code/go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

# SSH aliases
alias sshkjs3="ssh kjs3@$KJS3_IP"
alias sshds="ssh ubuntu@$DOORSTEPS_BOT_IP" # doorsteps bot on Lightsail

# Godammit Spotlight! Keep those apps in your index!
alias fuckyouspotlight="sudo mdutil -a -i off && sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist && sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist && sudo mdutil -a -i on"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
